# Service provides a stable internal network endpoint for the FastAPI Pods.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devorecruiter-api-back.fullname" . }}
  labels:
    {{- include "devorecruiter-api-back.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  # The Service sends traffic only to Pods with these selector labels.
  selector:
    {{- include "devorecruiter-api-back.selectorLabels" . | nindent 4 }}
